export const events = [
    {
        name: 'Concierto en el parque',
        categoryId: 1,
        direction: 'Parque Central, Calle Principal',
        description:
            'Disfruta de una tarde llena de música en vivo en el hermoso Parque Central. Varios artistas locales se presentarán en este evento gratuito para toda la familia.',
        onlyAdults: false,
        isFree: true,
        endDate: '2023-06-10',
        startDate: '2023-06-08',
        time: '18:00',
        price: 44440,
        tags: ['1', '2', '5'],
    },
    {
        name: 'Exposición de arte contemporáneo',
        categoryId: 2,
        direction: 'Galería de Arte Moderno, Avenida Principal',
        description:
            'Ven y admira una increíble colección de obras de arte contemporáneo de artistas reconocidos a nivel nacional e internacional. Esta exposición es solo para adultos y tiene una tarifa de entrada.',
        onlyAdults: true,
        isFree: false,
        endDate: '2023-06-15',
        startDate: '2023-06-12',
        time: '10:00',
        price: 2000,
        tags: ['3', '7'],
    },

    {
        name: 'Festival gastronómico',
        categoryId: 3,
        direction: 'Plaza de la Ciudad, Calle Principal',
        description:
            'Descubre una variedad de deliciosos platos preparados por los mejores chefs de la región en este emocionante festival gastronómico. La entrada es gratuita, pero los alimentos tienen un costo.',
        onlyAdults: false,
        isFree: true,
        endDate: '2023-06-30',
        startDate: '2023-06-28',
        time: '17:30',
        price: 5000,
        tags: ['2', '4', '8', '10'],
    },
    {
        name: 'Concierto de rock',
        categoryId: 4,
        direction: 'Estadio Principal, Avenida Central',
        description:
            'Disfruta de un increíble concierto de rock con bandas reconocidas a nivel internacional. Este evento es apto para todas las edades y la entrada es gratuita.',
        onlyAdults: false,
        isFree: true,
        endDate: '2023-06-10',
        startDate: '2023-06-08',
        time: '20:00',
        price: 33420,
        tags: ['1', '2', '5'],
    },
    {
        name: 'Feria de arte local',
        categoryId: 5,
        direction: 'Centro Cultural, Calle Principal',
        description:
            'Descubre el talento artístico local en esta feria de arte. Habrá exposiciones, demostraciones y venta de obras de artistas emergentes. La entrada es gratuita.',
        onlyAdults: false,
        isFree: true,
        endDate: '2023-06-15',
        startDate: '2023-06-12',
        time: '11:00',
        price: 2342340,
        tags: ['3', '7'],
    },
    {
        name: 'Festival de cine independiente',
        categoryId: 6,
        direction: 'Cine Central, Avenida Principal',
        description:
            'Sumérgete en el mundo del cine independiente con proyecciones de películas de diferentes géneros y temáticas. Disfruta de una experiencia cinematográfica única. Entrada con costo.',
        onlyAdults: false,
        isFree: false,
        endDate: '2023-06-20',
        startDate: '2023-06-18',
        time: '16:30',
        price: 50,
        tags: ['5', '8', '10'],
    },
    {
        name: 'Taller de cocina saludable',
        categoryId: 7,
        direction: 'Escuela de Cocina, Calle Principal',
        description:
            'Aprende a preparar deliciosos platos saludables en este taller de cocina. Descubre técnicas y recetas para una alimentación equilibrada. Cupos limitados, reserva tu lugar.',
        onlyAdults: true,
        isFree: false,
        endDate: '2023-06-25',
        startDate: '2023-06-23',
        time: '14:00',
        price: 1230,
        tags: ['2', '4', '9'],
    },
    {
        name: 'Exposición de fotografía',
        categoryId: 8,
        direction: 'Galería de Arte, Avenida Principal',
        description:
            'Admira las mejores obras fotográficas de artistas locales e internacionales en esta exposición. Explora distintos estilos y temáticas fotográficas. Entrada gratuita para menores de 18 años.',
        onlyAdults: false,
        isFree: true,
        endDate: '2023-06-30',
        startDate: '2023-06-28',
        time: '12:00',
        price: 3330,
        tags: ['6', '7', '10'],
    },
    {
        name: 'Festival de música electrónica',
        categoryId: 9,
        direction: 'Parque de la Ciudad, Avenida Principal',
        description:
            'Sumérgete en el mundo de la música electrónica con DJ reconocidos a nivel internacional. Disfruta de un ambiente vibrante y energético. Entrada con costo.',
        onlyAdults: true,
        isFree: false,
        endDate: '2023-07-05',
        startDate: '2023-07-03',
        time: '22:00',
        price: 830,
        tags: ['2', '5', '7'],
    },
    {
        name: 'Exposición de esculturas',
        categoryId: 10,
        direction: 'Museo de Arte Moderno, Calle Secundaria',
        description:
            'Admira las impresionantes esculturas de artistas contemporáneos en esta exposición única. Explora diferentes materiales y técnicas escultóricas. Entrada gratuita para estudiantes.',
        onlyAdults: false,
        isFree: true,
        endDate: '2023-07-10',
        startDate: '2023-07-07',
        time: '13:00',
        price: 550,
        tags: ['4', '8', '9'],
    },
    {
        name: 'Festival de teatro callejero',
        categoryId: 11,
        direction: 'Calles del Centro, Avenida Principal',
        description:
            'Disfruta de espectáculos teatrales en las calles de la ciudad. Actores y compañías teatrales mostrarán su talento en espacios públicos. Entrada gratuita para todo público.',
        onlyAdults: false,
        isFree: true,
        endDate: '2023-07-15',
        startDate: '2023-07-12',
        time: '17:00',
        price: 100,
        tags: ['1', '6', '7'],
    },
    {
        name: 'Conferencia sobre innovación tecnológica',
        categoryId: 12,
        direction: 'Centro de Convenciones, Avenida Principal',
        description:
            'Aprende sobre las últimas tendencias en innovación tecnológica en esta conferencia. Expertos en el campo compartirán conocimientos y experiencias. Entrada con costo.',
        onlyAdults: true,
        isFree: false,
        endDate: '2023-07-20',
        startDate: '2023-07-18',
        time: '09:00',
        price: 50,
        tags: ['3', '10'],
    },
    {
        name: 'Feria de artesanías',
        categoryId: 13,
        direction: 'Plaza del Mercado, Calle Principal',
        description:
            'Explora una amplia variedad de artesanías locales en esta feria. Encuentra productos únicos y apoya a los artesanos de la región. Entrada gratuita.',
        onlyAdults: false,
        isFree: true,
        endDate: '2023-07-25',
        startDate: '2023-07-22',
        time: '10:30',
        price: 20,
        tags: ['5', '8', '11'],
    },
    {
        name: 'Festival de Jazz en el Parque',
        categoryId: 14,
        direction: 'Parque Central, Calle Principal',
        description:
            'Disfruta de una noche mágica con música de jazz en vivo interpretada por reconocidos artistas internacionales. Este evento al aire libre es gratuito y apto para todas las edades.',
        onlyAdults: false,
        isFree: true,
        endDate: '2023-07-05',
        startDate: '2023-07-03',
        time: '19:00',
        price: 0,
        tags: ['1', '3', '7'],
    },
    {
        name: 'Exposición de Arte Aborigen',
        categoryId: 15,
        direction: 'Galería de Arte Contemporáneo, Avenida Principal',
        description:
            'Sumérgete en la riqueza cultural de las artes aborígenes con esta exposición. Descubre obras tradicionales y contemporáneas que representan la identidad y la historia de diversas comunidades indígenas. Entrada gratuita.',
        onlyAdults: false,
        isFree: true,
        endDate: '2023-07-10',
        startDate: '2023-07-07',
        time: '10:00',
        price: 0,
        tags: ['4', '6', '9'],
    },
    {
        name: 'Festival de Cine de Terror',
        categoryId: 16,
        direction: 'Cine Central, Calle Secundaria',
        description:
            'Si te gusta el cine de terror, no te puedes perder este festival. Disfruta de proyecciones de películas escalofriantes y vive la adrenalina en cada función. Entrada con costo.',
        onlyAdults: true,
        isFree: false,
        endDate: '2023-07-15',
        startDate: '2023-07-12',
        time: '20:30',
        price: 80,
        tags: ['2', '5', '8'],
    },
    {
        name: 'Conferencia de Innovación y Tecnología',
        categoryId: 17,
        direction: 'Centro de Convenciones, Avenida Principal',
        description:
            'Descubre las últimas tendencias en innovación y tecnología en esta conferencia. Expertos de renombre compartirán conocimientos y perspectivas sobre el futuro digital. Entrada con costo.',
        onlyAdults: true,
        isFree: false,
        endDate: '2023-07-20',
        startDate: '2023-07-18',
        time: '09:30',
        price: 50,
        tags: ['3', '9', '10'],
    },
    {
        name: 'Feria Gastronómica Internacional',
        categoryId: 18,
        direction: 'Plaza de la Ciudad, Avenida Principal',
        description:
            'Embárcate en un viaje culinario alrededor del mundo en esta feria gastronómica. Prueba platos exquisitos preparados por reconocidos chefs internacionales. Entrada gratuita, costo de alimentos y bebidas.',
        onlyAdults: false,
        isFree: true,
        endDate: '2023-07-25',
        startDate: '2023-07-22',
        time: '17:00',
        price: 0,
        tags: ['5', '7', '11'],
    },
    {
        name: 'Festival de Arte Urbano',
        categoryId: 19,
        direction: 'Centro de la Ciudad, Calle Principal',
        description:
            'Disfruta de una explosión de creatividad en el Festival de Arte Urbano. Murales, graffiti, performances y más te esperan en este evento gratuito para todo público.',
        onlyAdults: false,
        isFree: true,
        endDate: '2023-08-05',
        startDate: '2023-08-02',
        time: '14:00',
        price: 0,
        tags: ['4', '6', '7'],
    },
    {
        name: 'Concierto de Música Clásica',
        categoryId: 20,
        direction: 'Teatro Principal, Avenida Central',
        description:
            'Sumérgete en la belleza de la música clásica con este concierto sinfónico. Disfruta de obras maestras interpretadas por una orquesta de renombre internacional. Entrada con costo.',
        onlyAdults: false,
        isFree: false,
        endDate: '2023-08-10',
        startDate: '2023-08-07',
        time: '19:30',
        price: 100,
        tags: ['2', '8', '10'],
    },
    {
        name: 'Taller de Fotografía Nocturna',
        categoryId: 21,
        direction: 'Estudio Fotográfico, Calle Secundaria',
        description:
            'Aprende las técnicas y secretos para capturar imágenes impresionantes durante la noche en este taller de fotografía especializado. Cupos limitados, se requiere inscripción previa.',
        onlyAdults: true,
        isFree: false,
        endDate: '2023-08-15',
        startDate: '2023-08-12',
        time: '21:00',
        price: 60,
        tags: ['5', '9'],
    },
    {
        name: 'Feria de Diseño y Moda',
        categoryId: 22,
        direction: 'Centro de Convenciones, Avenida Principal',
        description:
            'Descubre las últimas tendencias en diseño y moda en esta feria. Exposiciones, desfiles, y venta de productos de diseñadores emergentes y consagrados. Entrada con costo.',
        onlyAdults: false,
        isFree: false,
        endDate: '2023-08-20',
        startDate: '2023-08-18',
        time: '10:00',
        price: 40,
        tags: ['1', '3', '10'],
    },
    {
        name: 'Conferencia de Medio Ambiente',
        categoryId: 23,
        direction: 'Auditorio Municipal, Calle Principal',
        description:
            'Aprende sobre los desafíos ambientales actuales y las soluciones sostenibles en esta conferencia. Expertos en medio ambiente compartirán su conocimiento y experiencias. Entrada gratuita.',
        onlyAdults: false,
        isFree: true,
        endDate: '2023-08-25',
        startDate: '2023-08-22',
        time: '15:00',
        price: 0,
        tags: ['6', '7', '11'],
    },
    {
        name: 'Festival de Cine Independiente',
        categoryId: 24,
        direction: 'Cineclub Municipal, Avenida Principal',
        description:
            'Sumérgete en el mundo del cine independiente con este festival. Disfruta de proyecciones de películas de diversas temáticas y géneros. Entrada gratuita para estudiantes.',
        onlyAdults: false,
        isFree: true,
        endDate: '2023-09-05',
        startDate: '2023-09-02',
        time: '17:30',
        price: 0,
        tags: ['4', '7', '9'],
    },
    {
        name: 'Exposición de Arte Contemporáneo',
        categoryId: 25,
        direction: 'Galería de Arte Moderno, Avenida Central',
        description:
            'Admira una colección de obras de arte contemporáneo de artistas locales e internacionales. Explora diferentes estilos y expresiones artísticas. Entrada gratuita.',
        onlyAdults: false,
        isFree: true,
        endDate: '2023-09-10',
        startDate: '2023-09-07',
        time: '11:00',
        price: 0,
        tags: ['2', '8'],
    },
    {
        name: 'Concierto de Rock Alternativo',
        categoryId: 26,
        direction: 'Estadio Municipal, Calle Principal',
        description:
            'Vive la energía del rock alternativo en este concierto inolvidable. Bandas destacadas del género te harán vibrar con sus mejores canciones. Entrada con costo.',
        onlyAdults: false,
        isFree: false,
        endDate: '2023-09-15',
        startDate: '2023-09-12',
        time: '20:00',
        price: 70,
        tags: ['3', '6', '10'],
    },
];
