import './globals.css';
import { Inter } from 'next/font/google';
import { Providers } from './store/provider';
import { Footer } from './common/components/Footer';
import { Navbar } from './common/components/Navbar';
import { MuiThemeProvider } from './styles/MuiThemeProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'EventTo',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Providers>
        <body>
          <MuiThemeProvider>
            <Navbar />
            {children}
          </MuiThemeProvider>
        </body>
      </Providers>
    </html>
  );
}
