<<<<<<< HEAD
'use client';
import { MuiThemeProvider } from './styles/MuiThemeProvider';
import './globals.css';
import { Inter, Outfit } from 'next/font/google';
import { Providers } from './store/provider';
import { Footer } from './common/components/Footer';
import { Navbar } from './common/components/Navbar';
import Container from '@mui/material/Container';
import Head from 'next/head';

const inter = Outfit({ subsets: ['latin'] });
=======
import './globals.css';
import { Inter } from 'next/font/google';
import { Providers } from './store/provider';
import { Footer } from './common/components/Footer';
import { Navbar } from './common/components/Navbar';
import { MuiThemeProvider } from './styles/MuiThemeProvider';

const inter = Inter({ subsets: ['latin'] });
>>>>>>> 03d406f528edc32f5258a426a3c2bca5246642e8

export const metadata = {
  title: 'EventTo',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
<<<<<<< HEAD
      <Head>
        <title>NeoVest SignIn</title>
      </Head>
      {/* <Providers> */}
      <body>
        <MuiThemeProvider>
          <Navbar />
          <Container fixed>{children}</Container>
        </MuiThemeProvider>
      </body>
      {/* </Providers> */}
=======
      <Providers>
        <body>
          <MuiThemeProvider>
            <Navbar />
            {children}
          </MuiThemeProvider>
        </body>
      </Providers>
>>>>>>> 03d406f528edc32f5258a426a3c2bca5246642e8
    </html>
  );
}
